name: Deploy para VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Buildar com Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build shadowJar

      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ env.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Enviar JAR para VPS
        run: |
          scp build/libs/agendei.jar ${{ env.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ env.VPS_TARGET_DIR }}/app.jar

      - name: Executar script remoto na VPS
        run: |
          ssh ${{ env.VPS_USER }}@${{ env.VPS_HOST }} "cd ${{ env.VPS_TARGET_DIR }} && ./deploy.sh"
